spring:
  application:
    name: le-minh-chien-coder
  profiles:
    active: dev
  #    active: "@spring.profiles.active@"
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

server:
  servlet:
    context-path: /api

# Cấu hình OpenAPI chung cho mọi môi trường
open:
  api:
    title: Management Library Api Documents
    version: 1.0
    description: Management Library Documents description
    serverName: server

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    csrf:
      enabled: true


